apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulseboard-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pulseboard-api
  template:
    metadata:
      labels:
        app: pulseboard-api
    spec:
      containers:
        - name: pulseboard-api
          image: pulseboard-api:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: pulseboard-db-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pulseboard-db-secret
                  key: POSTGRES_PASSWORD
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: pulseboard-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: pulseboard-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: pulseboard-db-secret
                  key: POSTGRES_DB
            - name: DATABASE_URL
              value: "postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"
